package com.memely.ui.fonts

import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import android.graphics.Typeface
import com.memely.R

/**
 * Central catalog for app font families using actual bundled TTF/OTF files.
 * 
 * These fonts are loaded from res/font/ and can be used both in Compose UI and
 * when saving memes to disk (via Typeface lookup).
 * 
 * Font Categories:
 * - SYSTEM: Platform fallbacks (always available)
 * - CUSTOM: User-selected custom fonts from res/font/
 * 
 * NOTE: Font resource IDs are auto-generated by Android from TTF/OTF filenames
 * Format: filename converted to lowercase with hyphens/special chars removed
 * E.g., "ArianaVioleta-dz2K.ttf" -> R.font.arianavioleta_dz2k
 */
object FontCatalog {
    
    // ===== SYSTEM FONTS (Platform Fallbacks) =====
    val Sans: FontFamily = FontFamily.SansSerif
    val Serif: FontFamily = FontFamily.Serif
    val Monospace: FontFamily = FontFamily.Monospace
    val Cursive: FontFamily = FontFamily.Cursive
    
    // ===== CUSTOM FONTS (from res/font/) =====
    // Creative/Display Fonts
    // Resource names follow Android convention: lowercase filename without extension, special chars as underscores
    val ArianaVioleta: FontFamily = FontFamily(Font(R.font.arianavioleta_dz2k))
    val BeckyTahlia: FontFamily = FontFamily(Font(R.font.beckytahlia_mp6r))
    val BelieveIt: FontFamily = FontFamily(Font(R.font.believeit_dvle))
    val Branda: FontFamily = FontFamily(Font(R.font.branda_yolq))
    val ChrustyRock: FontFamily = FontFamily(Font(R.font.chrustyrock_orla))
    val CookieCrisp: FontFamily = FontFamily(Font(R.font.cookiecrisp_l36ly))
    val Freedom: FontFamily = FontFamily(Font(R.font.freedom_10em))
    val ShadeBlue: FontFamily = FontFamily(Font(R.font.shadeblue_2oozx))
    val ShortBaby: FontFamily = FontFamily(Font(R.font.shortbaby_mg2w))
    val ToThePoint: FontFamily = FontFamily(Font(R.font.tothepointregular_n9y4))
    
    /**
     * All available font families for selection in the editor
     * Organized by category for UI presentation
     */
    data class FontOption(
        val name: String,
        val fontFamily: FontFamily,
        val resourceId: Int,  // For Typeface lookup when saving
        val category: String = "Custom"
    )
    
    val allFonts = listOf(
        // System fonts
        FontOption("Sans Serif", Sans, 0, "System"),
        FontOption("Serif", Serif, 0, "System"),
        FontOption("Monospace", Monospace, 0, "System"),
        FontOption("Cursive", Cursive, 0, "System"),
        
        // Custom fonts
        FontOption("Ariana Violeta", ArianaVioleta, R.font.arianavioleta_dz2k, "Display"),
        FontOption("Becky Tahlia", BeckyTahlia, R.font.beckytahlia_mp6r, "Display"),
        FontOption("Believe It", BelieveIt, R.font.believeit_dvle, "Display"),
        FontOption("Branda", Branda, R.font.branda_yolq, "Display"),
        FontOption("Chrusty Rock", ChrustyRock, R.font.chrustyrock_orla, "Display"),
        FontOption("Cookie Crisp", CookieCrisp, R.font.cookiecrisp_l36ly, "Display"),
        FontOption("Freedom", Freedom, R.font.freedom_10em, "Display"),
        FontOption("Shade Blue", ShadeBlue, R.font.shadeblue_2oozx, "Display"),
        FontOption("Short Baby", ShortBaby, R.font.shortbaby_mg2w, "Display"),
        FontOption("To The Point", ToThePoint, R.font.tothepointregular_n9y4, "Display"),
    )
    
    /**
     * Get FontOption by FontFamily for UI display
     */
    fun getFontOptionByFamily(fontFamily: FontFamily): FontOption {
        return allFonts.firstOrNull { it.fontFamily == fontFamily } 
            ?: FontOption("Sans Serif", Sans, 0, "System")
    }
    
    /**
     * Get FontOption by name for selection
     */
    fun getFontOptionByName(name: String): FontOption {
        return allFonts.firstOrNull { it.name.equals(name, ignoreCase = true) }
            ?: FontOption("Sans Serif", Sans, 0, "System")
    }
    
    /**
     * Create Typeface for Android Canvas drawing (used in MemeFileSaver)
     * Maps FontFamily to appropriate Typeface for rendering on canvas
     */
    fun getFontTypeface(fontFamily: FontFamily, context: android.content.Context): Typeface {
        return when (fontFamily) {
            Sans -> Typeface.SANS_SERIF
            Serif -> Typeface.SERIF
            Monospace -> Typeface.MONOSPACE
            Cursive -> Typeface.DEFAULT  // Fallback - Cursive not well supported on Canvas
            else -> {
                // Try to find custom font resource
                val fontOption = getFontOptionByFamily(fontFamily)
                if (fontOption.resourceId != 0) {
                    androidx.core.content.res.ResourcesCompat.getFont(context, fontOption.resourceId)
                        ?: Typeface.DEFAULT
                } else {
                    Typeface.DEFAULT
                }
            }
        }
    }
}
